version: 2
updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: ⬆
  # Python
  - package-ecosystem: "pnpm"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: ⬆
